name: Publish to crates.io

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cargo publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
